version: '3'

services:
  mvc.server.auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  mvc.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat
